require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BansController do

  def mock_ban(stubs={})
    @mock_ban ||= mock_model(Ban, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all bans as @bans" do
      Ban.stub(:all) { [mock_ban] }
      get :index
      assigns(:bans).should eq([mock_ban])
    end
  end

  describe "GET show" do
    it "assigns the requested ban as @ban" do
      Ban.stub(:find).with("37") { mock_ban }
      get :show, :id => "37"
      assigns(:ban).should be(mock_ban)
    end
  end

  describe "GET new" do
    it "assigns a new ban as @ban" do
      Ban.stub(:new) { mock_ban }
      get :new
      assigns(:ban).should be(mock_ban)
    end
  end

  describe "GET edit" do
    it "assigns the requested ban as @ban" do
      Ban.stub(:find).with("37") { mock_ban }
      get :edit, :id => "37"
      assigns(:ban).should be(mock_ban)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ban as @ban" do
        Ban.stub(:new).with({'these' => 'params'}) { mock_ban(:save => true) }
        post :create, :ban => {'these' => 'params'}
        assigns(:ban).should be(mock_ban)
      end

      it "redirects to the created ban" do
        Ban.stub(:new) { mock_ban(:save => true) }
        post :create, :ban => {}
        response.should redirect_to(ban_url(mock_ban))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ban as @ban" do
        Ban.stub(:new).with({'these' => 'params'}) { mock_ban(:save => false) }
        post :create, :ban => {'these' => 'params'}
        assigns(:ban).should be(mock_ban)
      end

      it "re-renders the 'new' template" do
        Ban.stub(:new) { mock_ban(:save => false) }
        post :create, :ban => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ban" do
        Ban.stub(:find).with("37") { mock_ban }
        mock_ban.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ban => {'these' => 'params'}
      end

      it "assigns the requested ban as @ban" do
        Ban.stub(:find) { mock_ban(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ban).should be(mock_ban)
      end

      it "redirects to the ban" do
        Ban.stub(:find) { mock_ban(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ban_url(mock_ban))
      end
    end

    describe "with invalid params" do
      it "assigns the ban as @ban" do
        Ban.stub(:find) { mock_ban(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ban).should be(mock_ban)
      end

      it "re-renders the 'edit' template" do
        Ban.stub(:find) { mock_ban(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ban" do
      Ban.stub(:find).with("37") { mock_ban }
      mock_ban.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the bans list" do
      Ban.stub(:find) { mock_ban }
      delete :destroy, :id => "1"
      response.should redirect_to(bans_url)
    end
  end

end
